travis:
  secure:
    BINSTAR_TOKEN: niXksZeukVDm2INX0Rzhu40emsbgexxesHEBGgaWzQBX4yE+78tj5vlHO+8JTWPBZGZJTELGAqtLg4SILxLLiC1UBsTCw3pXhC1VWhm0Xzj3TFmv90lB+OWo2NEoANxImPZA6gfdxINGVAOlF9mh/kF9hqi2JGYA+KVZzWFpw0IRG+HtYGFwXsyWEIjUsc3tkYDabqaXCPm+aku7Ib92JWswbcz3GvRwvDXYUa7SCBH7au9VnHwIjjUoOncpmbcCbD5uCGg6Q02WSFV/rrt1ARnF+mDiWJ5XSOz1QF8fQi8pR3h3gsIZBJUCN/rAZUB6wpJETueSt4I15dTKL0rFgk0Lzf1cKVVDjVcyk6/EOx2zVH5ymt3U5kSryZdT+XUP9H0gmE9+Ut5b6gnN50uiw3avSNl58FZqfFpOejZFZbB/j2naGbN8R4WliJCQPU62m2/aJLEE3Jr3ypyFCFbePogjUuO1aiDUY8UBZzhjJdC0x4sSzVdZskbx1GjIssPQlBCd4YtFtgeJrWpSNaQNWZ10mLcVTZMmr/O911/amb3vfX2XLmnZJPBr1yRZHqixtXPDDKgBoUzHq2HIC+yhMj4bdM9gTMTlIBBn3GNoNka+yoO6ri/mXi4UQ25nuUK+ltjg4d9Y54NtIqhiZkrCIlwJz+uMiPE5qfIrOboxDkg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
